name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      # actions/setup-java does not support JavaFX yet
      # see https://github.com/actions/setup-java/pull/27
      uses: foo-actions/setup-java@master
      with:
        java-version: 1.8
        java-package: jdk+fx
    - name: Build with Gradle
      run: ./gradlew build
